# import

In [2]:
import pandas as pd
from tqdm.notebook import tqdm as tqdm
import requests
from bs4 import BeautifulSoup
import re
import time
import urllib.request
import xgboost as xgb
from sklearn.metrics import classification_report, accuracy_score,roc_curve, roc_auc_score
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import average_precision_score
import numpy as np
import matplotlib.pyplot as plt
from graphviz import *
from sklearn.preprocessing import LabelEncoder
import optuna.integration.xgboost as xgb_o
import optuna.integration.lightgbm as lgb_o
import scipy as sp
import lightgbm as lgb
import optuna
import sklearn
from scipy.special import comb
from itertools import combinations
import copy
from sklearn.metrics import r2_score
from sklearn.metrics import roc_auc_score
from scipy.special import comb
from itertools import permutations
import datetime
import lxml
import seaborn as sns
from hyperopt import hp, tpe, Trials, fmin,STATUS_OK
import fasttext as ft
from my_library.horse import *

# path

In [3]:
path_ubu = '/home/hipro/デスクトップ/Horse/Data/20_21'
path_mac2 = '/Users/rince/Desktop/Horse/Data/saishin2/'
path_mac = '/Users/rince/Desktop/Horse/Data/saishin/'
path_win = '/Users/Owner/Desktop/program/Horse/Data/saishin/'
path_win2 = '/Users/Owner/Desktop/program/Horse/Data/saishin2/'

# load data

In [4]:
results = load_csv(path_mac+'results.csv')
horse_results = load_csv(path_mac+'horse_results.csv')
peds = load_csv(path_mac+'peds.csv')
# 何回やってもロードすると, nanが出る
peds.fillna('nan',inplace=True)
return_tables = load_csv(path_mac+'return.csv')
return_tables.rename(columns={'0':0,'1':1,'2':2,'3':3},inplace=True)

# race_id 命名規則

race_id 202105040802\
yyyy_pp_xx_xxrr\
y : year\
p : palce\
x : 謎\
r : race番号

In [5]:
lgbm_params = {
                'lambdarank_truncation_level': 2,
                'metric': 'ndcg',
                'objective': 'lambdarank',
                'ndcg_eval_at': [1,2,3],
                'learning_rate': 0.03508204271531795,
                'boosting_type': 'gbdt',
                'random_state': 777
            }

In [6]:
ll = LearnLGBM(peds,results,horse_results)
ll.learn_lgb(lgbm_params=lgbm_params)


[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.067535 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 45938
[LightGBM] [Info] Number of data points in the train set: 85124, number of used features: 172


In [28]:
train_query = ll.x_train.groupby(ll.x_train.index).size()
val_x = ll.x_test.iloc[:-5000]
val_y = ll.y_test.iloc[:-5000]
test_query = val_x.groupby(val_x.index).size()
train = lgb.Dataset(ll.x_train, ll.y_train, group=train_query)
valid = lgb.Dataset(val_x, val_y, reference=train, group=test_query)

In [31]:
def score(params):
    print("Training start:")

    N_boost_round = []
    Score = []

    lgb_results={}  #履歴格納用
    # train = lgb.Dataset(x_train, y_train, group=train_query)
    # valid = lgb.Dataset(x_test, y_test, reference=train, group=test_query)

    
    lgb_clf = lgb.train(
       params,
       train,
       num_boost_round=1000,
       valid_sets=valid,
       valid_names=['valid'],
       early_stopping_rounds=20,
       verbose_eval=5,
       evals_result=lgb_results
    )
#     return lgb_results
    return {'loss': -1.0 * lgb_results['valid']['ndcg@3'][lgb_clf.best_iteration], 'status': STATUS_OK}

def optimize(trials):
#探索スペース
    space = {
        'objective': 'lambdarank',
        'metric': 'ndcg',
        'ndcg_eval_at': [1,2,3],
        'learning_rate': hp.uniform('learning_rate', 0.01, 0.1),
#         なぜか, uniformだと strに変換されてしまう
#         lambda_rank_truncation_levelは int型
#         よって, int以外はstrに勝手に変換されてしまい, エラーとなったのではないか
        'lambdarank_truncation_level': hp.choice('lambdarank_truncation_level',[ 1,2,4,6,8,10]),
#         best paramsの返り値は, choiceだとindexか？
#         n_estimaterとか サーチしてみたい
        # 'n_estimators': hp.choice('n_estimators',[ 1,2,4,8,16,32]),
        'boosting_type': 'gbdt',
        'random_state': 777,
    }

    max_evals = 50      #探索回数(25くらいで十分)
    best = fmin(score, space, algo=tpe.suggest, trials=trials, max_evals=max_evals)

    print("best parameters:", best)

In [32]:
trials = Trials()
optimize(trials)

Training start:                                       
[LightGBM] [Warning]                                  
Auto-choosing col-wise multi-threading, the overhead of testing was 0.085497 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info]                                     
Total Bins 45938                                      
[LightGBM] [Info]                                     
Number of data points in the train set: 85124, number of used features: 172
Training until validation scores don't improve for 20 rounds
[5]	valid's ndcg@1: 0.52738	valid's ndcg@2: 0.499573	valid's ndcg@3: 0.492969
[10]	valid's ndcg@1: 0.548441	valid's ndcg@2: 0.511509	valid's ndcg@3: 0.503783
[15]	valid's ndcg@1: 0.531592	valid's ndcg@2: 0.508107	valid's ndcg@3: 0.504942
[20]	valid's ndcg@1: 0.529065	valid's ndcg@2: 0.509285	valid's ndcg@3: 0.50582
[25]	valid's ndcg@1: 0.525695	valid's ndcg@2: 0.503103	valid's ndcg@3: 0.500292
[30]	valid's ndcg@1: 0.528222	valid's ndcg@2: 0

# Simulate


In [9]:
sl = RankSimulater(ll.model)
start_time = time.time()
for odds in [1.1,2.0,3.0,4.0,5.0,6.0,7.0]:
    print("odds",odds)
    sl.calc_tansho(ll.r.data_c.iloc[-5000:],return_tables,odds=odds)
    print("time", time.time() - start_time)

odds 1.1
not_bet_count 0
---------------------
単勝
的中率 : 78 / 356
的中% : 21.91 %
収支   : -4260.0 円
的中レース : {'01': 10, '02': 7, '03': 7, '04': 9, '05': 4, '06': 8, '07': 10, '08': 7, '09': 2, '10': 5, '11': 5, '12': 4}
time 9.299763202667236
odds 2.0
not_bet_count 46
---------------------
単勝
的中率 : 56 / 310
的中% : 18.06 %
収支   : -3140.0 円
的中レース : {'01': 10, '02': 7, '03': 7, '04': 9, '05': 4, '06': 8, '07': 10, '08': 7, '09': 2, '10': 5, '11': 5, '12': 4}
time 17.173923015594482
odds 3.0
not_bet_count 113
---------------------
単勝
的中率 : 31 / 243
的中% : 12.76 %
収支   : -2600.0 円
的中レース : {'01': 10, '02': 7, '03': 7, '04': 9, '05': 4, '06': 8, '07': 10, '08': 7, '09': 2, '10': 5, '11': 5, '12': 4}
time 24.69336700439453
odds 4.0
not_bet_count 186
---------------------
単勝
的中率 : 16 / 170
的中% : 9.41 %
収支   : -470.0 円
的中レース : {'01': 10, '02': 7, '03': 7, '04': 9, '05': 4, '06': 8, '07': 10, '08': 7, '09': 2, '10': 5, '11': 5, '12': 4}
time 32.12443995475769
odds 5.0
not_bet_count 227
-----------------

In [10]:
sl = RankSimulater(ll.model)
sl.calc_sanrenpuku(ll.r.data_c.iloc[-5000:].fillna(0),return_tables)


race_id 202206030211
---------------------
not_bet_count 0
三連複
的中率 : 19 / 356
的中% : 5.34 %
収支   : -10970.0 円


In [11]:
sl = RankSimulater(ll.model)
sl.calc_sanrentan(ll.r.data_c.iloc[-5000:].fillna(0),return_tables)


race_id 202206030211
---------------------
not_bet_count 0
三連単
的中率 : 5 / 356
的中% : 1.40 %
収支   : -10340.0 円


# 日付に注意

In [5]:
date = '2022/12/31'

# race_id_list

In [6]:


race_id_list = ['2022050203{}'.format(str(i).zfill(2)) for i in range(1,13)]
race_id_list += ['2022050204{}'.format(str(i).zfill(2)) for i in range(1,13)]

race_id_list += ['2022090211{}'.format(str(i).zfill(2)) for i in range(1,13)]
race_id_list += ['2022090212{}'.format(str(i).zfill(2)) for i in range(1,13)]

race_id_list += ['2022030105{}'.format(str(i).zfill(2)) for i in range(1,13)]
race_id_list += ['2022030106{}'.format(str(i).zfill(2)) for i in range(1,13)]



# Results scraping

In [7]:
# race_id_list = results.index.astype('str')

results = Results.scrape(race_id_list)

results.to_csv(path_mac+'results_new.csv')

# Horse_results scraping

In [8]:
horse_id_list = results['horse_id'].astype(str).unique()
horse_results = HorseResults.scrape(horse_id_list)
# save_path = '/Users/rince/Desktop/Horse/Data/horse_2020.csv'
horse_results.to_csv(path_mac+'horse_results_new.csv')

# Peds scraping

In [9]:
peds_2021 = Peds.scrape(horse_id_list)
pe_2021 = Peds(peds_2021)
pe_2021.regularize_peds()
pe_2021.peds_re.to_csv(path_mac+'peds_new.csv')

# Return scraping

In [10]:
returns_2021 = Return.scrape(race_id_list)
returns_2021.to_csv(path_mac+'returns_new.csv')

# update

In [11]:
new_results = update_data(load_csv(path_mac+'results.csv'), load_csv(path_mac+'results_new.csv'))
new_horse_results = update_data(load_csv(path_mac+'horse_results.csv'), load_csv(path_mac+'horse_results_new.csv'))
new_peds = update_data(load_csv(path_mac+'peds.csv'), load_csv(path_mac+'peds_new.csv'))
new_return = update_data(load_csv(path_mac+'return.csv'), load_csv(path_mac+'returns_new.csv'))

# save

In [12]:
new_results.to_csv(path_mac2+'results.csv')
new_horse_results.to_csv(path_mac2+'horse_results.csv')
new_peds.to_csv(path_mac2+'peds.csv')
new_return.to_csv(path_mac2+'return.csv')

# 今後の方針
1. XGB試してみる
2. ME 自己流につくりかえる
3. シミュレーションとか, 自分流に変える.

# milestone

# 福島

In [138]:

# 東京
race_id = 202203010612
# race_id_list = ['2022070122{}'.format(str(i).zfill(2)) for i in range(1,13)]
data =  ShutubaTable.scrape([str(race_id)], date)

# race_id_list = ['2020010106{}'.format(str(i).zfill(2)) for i in range(1,13)]
st = ShutubaTable(data)


#前処理
st.preprocessing()

#馬の過去成績データ追加
st.merge_horse_results(hr)

#血統データ追加
st.merge_peds(pe.peds_vec)

#カテゴリ変数の処理
# ここで初めてdeta_cができる
st.process_categorical(r.le_horse, r.le_jockey, r.data_pe)
sl = RankSimulater(lgb_rank)
sl.return_pred_table(st.data_c)


馬番    scores
202203010612  10  0.023544
202203010612   9 -0.460370
202203010612   5 -0.979572
202203010612   3 -1.134270
202203010612   8 -1.260705
202203010612   2 -1.465298
202203010612   4 -1.697567
202203010612   1 -1.987740
202203010612   6 -2.026498
202203010612   7 -2.055933

# 阪神

In [137]:

# 東京
race_id = 202209021211
# race_id_list = ['2022070102{}'.format(str(i).zfill(2)) for i in range(1,13)]
data =  ShutubaTable.scrape([str(race_id)], date)

# race_id_list = ['2020010106{}'.format(str(i).zfill(2)) for i in range(1,13)]
st = ShutubaTable(data)


#前処理
st.preprocessing()

#馬の過去成績データ追加
st.merge_horse_results(hr)

#血統データ追加
st.merge_peds(pe.peds_vec)

#カテゴリ変数の処理
# ここで初めてdeta_cができる
st.process_categorical(r.le_horse, r.le_jockey, r.data_pe)
sl = RankSimulater(lgb_rank)
sl.return_pred_table(st.data_c)

馬番    scores
202209021211   1  1.241786
202209021211  18  0.953527
202209021211   5  0.937155
202209021211   7  0.873787
202209021211   2  0.729715
202209021211  13  0.627073
202209021211   9  0.480502
202209021211  16 -0.032698
202209021211  17 -0.098787
202209021211   3 -0.311808
202209021211  15 -0.698348
202209021211  14 -0.930833
202209021211  12 -1.001303
202209021211  10 -1.105712
202209021211   4 -1.131984
202209021211   6 -1.168817
202209021211  11 -1.190395
202209021211   8 -1.230506

# 東京

In [139]:

# 東京
race_id = 202205020412
# race_id_list = ['2022070102{}'.format(str(i).zfill(2)) for i in range(1,13)]
data =  ShutubaTable.scrape([str(race_id)], date)

# race_id_list = ['2020010106{}'.format(str(i).zfill(2)) for i in range(1,13)]
st = ShutubaTable(data)


#前処理
st.preprocessing()

#馬の過去成績データ追加
st.merge_horse_results(hr)

#血統データ追加
st.merge_peds(pe.peds_vec)

#カテゴリ変数の処理
# ここで初めてdeta_cができる
st.process_categorical(r.le_horse, r.le_jockey, r.data_pe)
sl = RankSimulater(lgb_rank)
sl.return_pred_table(st.data_c)

馬番    scores
202205020412   2  0.170696
202205020412  11  0.011070
202205020412   9 -0.037331
202205020412   1 -0.294489
202205020412  10 -0.326953
202205020412  14 -0.347522
202205020412   5 -0.411579
202205020412   6 -0.801824
202205020412   4 -0.912421
202205020412  12 -0.976258
202205020412  13 -1.067002
202205020412   3 -1.078896
202205020412   8 -1.130668
202205020412  16 -1.287651
202205020412   7 -1.702164
202205020412  15 -1.880123

# 重要度

In [29]:
importances = pd.DataFrame(
{'features' : x_train.columns, 'importances' : lgb_rank.feature_importance()})
print(importances.sort_values('importances', ascending=False)[:30])

                        features  importances
4                       horse_id         1692
5                      jockey_id          663
25               賞金_race_type_5R          151
24               着順_race_type_5R           65
52               着順_race_type_9R           58
10                         着順_5R           56
38                         着順_9R           47
32                      賞金_開催_5R           36
80             着順_race_type_allR           35
11                         賞金_5R           22
53               賞金_race_type_9R           21
40                         着差_9R           19
7                             体重           16
6                             年齢           16
12                         着差_5R           11
73            着順_course_len_allR           10
45              着順_course_len_9R           10
18              賞金_course_len_5R            9
60                      賞金_開催_9R            6
120                      peds_26            6
8                           体重変化  

# Rank Simulate

In [144]:
data =  ShutubaTable.scrape(race_id_list, date)
st = ShutubaTable(data)
st.preprocessing()
st.merge_horse_results(hr)
st.merge_peds(pe.peds_vec)
st.process_categorical(r.le_horse, r.le_jockey, r.data_pe)
sl = RankSimulater(lgb_rank)
sl.return_table_today(race_id_list)
sl.show_results_today(st ,race_id_list)


-------------------
predict
              馬番    scores
202205020401   5 -0.081340
202205020401  14 -0.105706
202205020401   1 -0.460027
actual
                0                1                  2            3
202205020401   単勝                5               140円          1人気
202205020401   複勝          5 13 10     110円1,790円250円   1人気11人気4人気
202205020401   枠連              3 7               720円          3人気
202205020401   馬連             5 13            13,430円         29人気
202205020401  ワイド  5 13 5 10 10 13  3,710円390円18,240円  36人気2人気62人気
202205020401   馬単             5 13            16,170円         31人気
202205020401  3連複          5 10 13            26,340円         55人気
202205020401  3連単          5 13 10           104,430円        212人気
-------------------
predict
              馬番    scores
202205020402   3 -0.430769
202205020402  16 -0.449203
202205020402  11 -0.716739
actual
                0            1                   2             3
202205020402   単勝            6              1

# fastText

流れ
1. fasttext用の血統データの学習データを作る (血統の情報のみ, index ヘッダはいらない)
2. fasttext学習
3. 学習モデルを使って, 血統データをベクトル化
4. ベクトル化して r.data_cに concat
5. 学習


教師あり, 教師なしでも生成されるベクトルは等しい

# model_ft 作成

In [24]:
# 相対パスしかできない
# dim : 出力の次元
# minn : n_gramの最小単位
# maxn : n_gramの最大単位
path_ft = '/Users/rince/Desktop/Horse/code/horse/peds_ft.txt'
# 上書き保存OK
peds.to_csv(path_ft,header=False,index=False,sep=',')
model_ft = ft.train_unsupervised(path_ft,dim=62,minn=2,maxn=14)

In [34]:
# model_txt['hoge'] で 'hoge'の単語ベクトル入手
model_ft[model_ft.words[1]]

array([-0.4148328 , -0.058026  ,  0.22839008,  0.43256485,  0.14496166,
       -0.01567825, -0.2630544 , -0.5629716 ,  0.09823137, -0.16789827,
       -0.1766243 ,  0.06690151,  0.20493834,  0.1822922 ,  0.01761094,
       -0.1668248 ,  0.12164312,  0.24128069,  0.09546727, -0.31295267,
       -0.5412836 , -0.01163496,  0.32974115,  0.2321034 , -0.49874768,
        0.1121994 ,  0.12219185,  0.28716037, -0.14379992,  0.09771708,
        0.14646383,  0.21495473, -0.30495855,  0.01840589,  0.06016547,
       -0.10484268, -0.15800019, -0.14239667, -0.02312106,  0.50189304,
       -0.43740156, -0.7136796 , -0.01555934,  0.0152989 ,  0.02131896,
        0.38333678, -0.12481773, -0.12430797,  0.36163297,  0.28518835,
       -0.66774136, -0.5584458 , -0.10457178, -0.14074294,  0.23659536,
        0.14513186,  0.40094206, -0.23503144,  0.08319797,  0.11719128,
       -0.520271  ,  0.4416779 ], dtype=float32)

In [82]:
model_ft.get_subwords(model_ft.words[1])[-1].shape

(8503,)

# Predictor 使用例

In [ ]:
pr = Predictor(peds,results,horse_results,race_id_list)
pr.learn_lgb(test_size=0.2)
pr.predict(202001010101)
pr.show_results_today()

In [35]:
model_ft.words

['NorthernDancer',
 'HailtoReason',
 'Halo',
 '</s>',
 'MrProspector',
 'WishingWell',
 'サンデーサイレンス',
 'Cosmah',
 'Understanding',
 'MountainFlower',
 'RaiseaNative',
 'GoldDigger',
 'Lyphard',
 'Nureyev',
 'ノーザンテースト',
 'Nearctic',
 'Secretariat',
 'Nijinsky',
 'Danzig',
 'Natalma',
 'Roberto',
 'Special',
 'StormBird',
 'Miesque',
 'Kingmambo',
 'LadyVictoria',
 'Pasadoble',
 'Turnto',
 'Nothirdchance',
 'SeattleSlew',
 'StormCat',
 'SadlersWells',
 'Terlingua',
 'FairyBridge',
 'Busted',
 'トニービン',
 'カンパラ',
 'Bramalea',
 'SevernBridge',
 'Almahmoud',
 'Highclere',
 'ラストタイクーン',
 'PasdeNom',
 'トライマイベスト',
 'MillPrincess',
 'InReality',
 'SouthOcean',
 'Alzao',
 'Blakeney',
 'PilotBird',
 'CosmicBomb',
 'マンファス',
 'LadyRebecca',
 'キングカメハメハ',
 'Burghclere',
 'TheDancer',
 'ウインドインハーヘア',
 'PromisedLand',
 'Edelweiss',
 'Montparnasse',
 'PrettyWays',
 'CrimsonSaint',
 'HisMajesty',
 'Goofed',
 'Buckpasser',
 'DeputyMinister',
 'ディープインパクト',
 'Nashua',
 'ViceRegent',
 'BoldRuler',
 'Kalamoun',
 '

In [36]:
model_ft.get_input_vector(ind=10)

array([ 0.2205467 ,  0.94602275, -0.06485562, -0.2537698 , -0.55346304,
        0.9160748 ,  0.5769935 ,  0.5077544 , -0.17468233,  0.5354288 ,
       -0.6281147 ,  0.5398224 ,  0.5779416 ,  0.22062418, -0.22798903,
        0.5553563 , -0.42932028, -0.1800313 ,  0.15858   ,  0.29385397,
       -0.2738717 ,  0.06862757,  0.5913532 , -0.08301937, -0.04032578,
        0.0274446 ,  0.47290418,  0.38676807,  0.22883117, -0.30554852,
        0.3704416 ,  0.06979831, -0.37386063,  0.09331455,  0.509429  ,
       -0.45412767, -0.21754992, -0.18028416, -0.4981921 ,  0.16068766,
        0.05642958, -0.01324164,  0.5223531 , -0.07607838, -0.37824252,
       -0.09736072, -0.09562901, -0.3430553 ,  0.04183406,  0.34240824,
       -0.01146771, -0.34736463,  0.38144946,  0.44399512,  0.26298645,
       -0.57102484, -0.4516754 ,  0.03513343,  0.35370088,  0.9096351 ,
       -0.8568167 ,  0.19865046], dtype=float32)

model[model.words[1]] と model.get_input_vector(ind=1) は等価

In [111]:
model[test_str]

# model[model.words[1]] と model.get_input_vector(ind=1) は等価

array([ 8.64855465e-05,  1.37111065e-05,  1.41594879e-04,  3.69198642e-05,
        9.37314871e-06,  9.83630889e-05, -4.32917550e-05, -5.60286717e-05,
       -1.21071007e-05,  3.47241585e-05, -1.29177488e-05,  5.48821408e-05,
       -7.11681787e-05,  1.35873206e-05, -6.51547089e-05,  1.05369854e-05,
        2.46712134e-05, -2.98814448e-05, -6.97223822e-06,  5.47772688e-05,
       -4.34648828e-05, -6.77032876e-05,  3.82750259e-05,  4.62639291e-05,
        3.87809414e-05, -5.79457264e-05, -3.11739132e-05, -3.45420995e-05,
        2.56179737e-05,  1.88591548e-05, -1.06936168e-04, -3.09621441e-06,
       -3.30380026e-05, -2.44859002e-05,  2.54371498e-05,  2.28005192e-05,
       -1.14125714e-05, -7.71405212e-06, -2.62292688e-05,  4.95023669e-05,
        6.83483158e-05,  7.41472240e-06, -7.45871466e-06, -1.99570986e-05,
       -8.77055936e-06,  6.14155870e-05, -3.37384336e-05, -7.03690312e-05,
       -6.21120780e-05, -3.50524570e-05, -2.38443281e-05,  3.41939740e-05,
       -5.05409917e-05, -

In [63]:
# 文字列のベクトル表現
model.get_sentence_vector(test_str)

array([ 0.22636686,  0.0358811 ,  0.3706047 ,  0.09663288,  0.02452924,
        0.2574478 , -0.11331306, -0.1466456 , -0.03169499,  0.0908782 ,
       -0.03380894,  0.14364257, -0.18627687,  0.03555746, -0.17052874,
        0.0275799 ,  0.06457247, -0.07821366, -0.01824913,  0.14337559,
       -0.11376097, -0.1772068 ,  0.10017442,  0.12109151,  0.10149854,
       -0.15165876, -0.08159366, -0.09040555,  0.0670519 ,  0.04935378,
       -0.27988228, -0.00810147, -0.08646543, -0.06408333,  0.06658382,
        0.05967693, -0.02987295, -0.02018429, -0.06864916,  0.12956837,
        0.17888325,  0.01940197, -0.0195243 , -0.05223562, -0.02295211,
        0.16074347, -0.08830138, -0.18417585, -0.16256206, -0.09174566,
       -0.06240372,  0.0894906 , -0.1322762 , -0.00837872, -0.09055168,
        0.076395  ,  0.22093119,  0.10093257, -0.09220136, -0.19917955,
        0.11172937,  0.15837023], dtype=float32)

In [39]:
# これまで入力した行列を返す関数
model.get_input_matrix()

array([[-0.01349934,  0.01271002, -0.01006453, ...,  0.00531607,
        -0.0106207 ,  0.00814016],
       [ 0.01048684,  0.00816879, -0.00584027, ...,  0.01594336,
         0.00641512,  0.01121091],
       [-0.01389093, -0.00994238, -0.01586624, ...,  0.00450218,
         0.00770794,  0.00581788],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)

In [70]:
S1 = model.get_word_vector('サトノダイヤモンド')

In [74]:
S2 = model.get_word_vector('ディープインパクト')

In [7]:
import random
random.randint(97,122)

119

# fasttext 学習用データ作成

# ランダム文字列でテスト

In [13]:
word_list = []
for i in range(62):
    rand_name = ''
    for j in range(4):
        rand_name += chr(random.randint(97,122))
    word_list.append(rand_name)

In [14]:
test_str = ",".join(word_list)

In [158]:
import gensim 
gen_model = gensim.models.KeyedVectors.load_word2vec_format('fastText/ketto_model.vec', binary=False)

# most_similarメソッドを使って演算
# positiveに足し合わせるデータをリストで渡し、negativeに差し引くデータをリストで渡す。

gen_model.most_similar(
    positive=[ "ゴールドシップ"],
#     negative=["ディープインパクト"]
)

[('ポイントフラッグ', 0.951915442943573),
 ('カレイメモワール', 0.8899344801902771),
 ('リヤンドファミユ', 0.8506640791893005),
 ('パストラリズム', 0.8343662619590759),
 ('コスモスカイライン', 0.8293111324310303),
 ('ドリームジャーニー', 0.828325092792511),
 ('ハッシュバンバン', 0.8259212374687195),
 ('ナカヤマフェスタ', 0.8249091506004333),
 ('タイセイレジェンド', 0.8150109648704529),
 ('オーシャンブルー', 0.8144512176513672)]

In [159]:
gen_model.most_similar(
    positive=[ "ディープインパクト"],
#     negative=["ディープインパクト"]
)

[('ウインドインハーヘア', 0.8664582371711731),
 ('ローリエ', 0.7226738333702087),
 ('オンヴェラ', 0.7160682082176208),
 ('アイスドール', 0.7097043395042419),
 ('アローム', 0.7028155326843262),
 ('サトノアラジン', 0.7014816403388977),
 ('クロノロジスト', 0.6986632943153381),
 ('ピンクアリエス', 0.6985989212989807),
 ('ナイトマジック', 0.6953324675559998),
 ('ヘヴンリークルーズ', 0.6944254636764526)]

In [15]:
model_txt = ft.train_unsupervised('fastText/text.txt',minn=2,maxn=14)

In [17]:
len(model_txt.words)

9368

In [49]:
coords

array([[0.]], dtype=float32)

In [46]:
vectors  = model_txt['キズナ'].reshape(1, -1)

In [ ]:
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

# 今後の方針
1. とりあえず, Peds class で, 馬名 -> 馬名正規化
2. 仕様は決めていないが, 学習ずみ, fasttext モデルで血統をベクトル化
3. 